### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by og2t** [tiberiuc/redux-react-firebase#1]
Hi Tiberiu,

The example uses `configureStore` from the `store` but it's not defined there.

```
import configureStore from './store'
const store = configureStore()
```

Can you post an example how to configure Firebase URL, since I am getting this error:

`Uncaught Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com`

Thanks!

**Comment by tiberiuc** [comment]
the example is not outdated , configureStore it is the default export from the store 

```
export default initialState => createStoreWithFirebase(rootReducer, initialState)
```

just being renamed as configureStore

the error you have is because the firebase cannot connect to your database as you didn't changed the URL for that ( you still use https://YOUR FIREBASE.firebaseio.com )

so you need to go to store.js in line 9 and use your own Firebase URL 

Let me know if you need more info

**Comment by og2t** [comment]
You're right. Thanks for clarification!
