### ISSUE TITLE
ES6/7 Decorator alternative

### ISSUE THREAD

**Issue by TrySpace** [tiberiuc/redux-react-firebase#20]
I see in the example (https://github.com/tiberiuc/redux-react-firebase/blob/master/example/App.js)

```
@firebase()
```

and then later:

```
@firebase( [
  '/todos', // if list is too large you can use ['/todos']
])
```

I'm not sure why this happens twice, and what the decorator does exactly, and what the alternative would be with ES5.

Also, the comment `// if list too large you can use  ['/todos']` I don't understand what this means, can you elaborate? (there is no difference in `'/todos'`)

**Comment by tiberiuc** [comment]
first version

```
@firebase( [
  '/todos', 
])
```

it is the equivalent for `firebase.ref.child('/todos').on('value', ..... )` that mean it will listen for value and each time a todo will change it will fetch the entire /todos tree as a single value. The problem is when you have a lot of todos, firebase have a limit of 10mb / node

while 

```
@firebase( [
  ['/todos'], 
])
```

it is the equivalent for 

```
firebase.ref.child('/todos').on('child_added', ..... )
firebase.ref.child('/todos').on('child_removed', ..... )
firebase.ref.child('/todos').on('child_changed', ..... )
firebase.ref.child('/todos').on('child_moved', ..... )
```

and it will fetch each todo item one by one and also listen for removed, changed, ... events and is setting them into redux store one by one

the result of each version it is the same, the difference it is how it is fetching the results from firebase and of course when you have huge data ( more then 10mb ) then first version will just not work

let me know if you have any other questions

**Comment by TrySpace** [comment]
How can I avoid the `@` decorator? Should I bind it with `.on` manually? And what should the `callback` do?
Or is there another way like:

`@firebase(['/todos']).bind(this)`

But maybe I'm misunderstanding the decorator.

Also, I still don't understand the usage of `@firebase()` in the example, is it necessary to initialize the thing? Because after it is used again, but then with `['todos']`...

**Comment by prescottprue** [comment]
+1 This would be good for those who don't want to include decorators.

**Comment by prescottprue** [comment]
@TrySpace [the simple example of redux-firebasev3](https://github.com/prescottprue/redux-firebasev3/blob/master/examples/simple/src/App.js#L59-L67) shows implementing without decorators where [the decorators example](https://github.com/prescottprue/redux-firebasev3/blob/master/examples/decorators/src/App.js#L12-L18) (interface is the same as this library)

Simple comparison:

#### With Decorators

``` js
@firebase(['/todos'])
@connect(
  ({firebase}) => ({
    todos: dataToJS(firebase, '/todos'),
    profile: pathToJS(firebase, 'profile')
  })
)
```

#### Without Decorators

``` js
const fbWrappedComponent = firebase(['/todos'])(App)

export default connect(
  ({firebase}) => ({
    todos: dataToJS(firebase, 'todos'),
    profile: pathToJS(firebase, 'profile')
  })
)(fbWrappedComponent)
```

I bet that @tiberiuc will add a similar example showing this in the future (he is just now back around).

**Comment by tiberiuc** [comment]
thank you @prescottprue  for your example
